"use client"
import Navbar from '@/components/bars/navbar'
import { Container } from '@mui/material'
export const metadata = {
    title: 'LBA virtual - Home',
    description: 'Generated by create next app',
    link : <link rel="shortcut icon" href="#"></link>
}

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <Container maxWidth="xl">
            <Navbar />
            {children}
        </Container>
    )
}
