import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from './providers/sessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'LBA virtual - Sign In/Login ',
  description: 'Generated by create next app',
  link : <link rel="shortcut icon" href="#"></link>
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
